# This file created by conda-build 3.23.3
# meta.yaml template originally from:
# C:\b\abs_dbjc7g0dh2\clone\recipe, last modified Thu Mar 16 21:40:13 2023
# ------------------------------------------------

package:
  name: keyring
  version: 23.13.1
source:
  sha256: ba2e15a9b35e21908d0aaf4e0a47acc52d6ae33444df0da2b49d41a46ef6d678
  url: https://pypi.io/packages/source/k/keyring/keyring-23.13.1.tar.gz
build:
  entry_points:
    - keyring = keyring.cli:main
  number: '0'
  script: C:\\b\\abs_dbjc7g0dh2\\croot\\keyring_1678999228878\\_h_env\\python.exe
    -m pip install . --no-deps -vv
  string: py311haa95532_0
requirements:
  host:
    - bzip2 1.0.8 he774522_0
    - ca-certificates 2023.01.10 haa95532_0
    - certifi 2022.12.7 py311haa95532_0
    - flit-core 3.6.0 pyhd3eb1b0_0
    - libffi 3.4.2 hd77b12b_6
    - openssl 1.1.1t h2bbff1b_0
    - packaging 23.0 py311haa95532_0
    - pip 22.3.1 py311haa95532_0
    - python 3.11.0 h966fe2a_3
    - setuptools 65.5.0 py311haa95532_0
    - setuptools-scm 7.0.4 py311haa95532_0
    - setuptools_scm 7.0.4 hd3eb1b0_0
    - sqlite 3.41.1 h2bbff1b_0
    - tk 8.6.12 h2bbff1b_0
    - toml 0.10.2 pyhd3eb1b0_0
    - tomli 2.0.1 py311haa95532_0
    - typing-extensions 4.4.0 py311haa95532_0
    - typing_extensions 4.4.0 py311haa95532_0
    - tzdata 2022g h04d1e81_0
    - vc 14.2 h21ff451_1
    - vs2015_runtime 14.27.29016 h5e58377_2
    - wheel 0.37.1 pyhd3eb1b0_0
    - wincertstore 0.2 py311haa95532_0
    - xz 5.2.10 h8cc25b3_1
    - zlib 1.2.13 h8cc25b3_0
  run:
    - importlib_metadata >=4.11.4
    - jaraco.classes
    - python >=3.11,<3.12.0a0
    - pywin32-ctypes >=0.2.0
test:
  commands:
    - pip check
    - py.test -v tests
    - keyring --help
  imports:
    - keyring
    - keyring.backends
    - keyring.util
  requires:
    - pip
    - pytest >=6
    - pytest-runner
    - setuptools_scm >=1.15.0
  source_files:
    - tests/*
about:
  description: 'The python keyring lib provides a easy way to access the system keyring

    service from python.  it can be used in any application that needs safe

    password storage.

    '
  dev_url: https://github.com/jaraco/keyring
  doc_url: https://pypi.org/project/keyring/
  home: https://github.com/jaraco/keyring
  license: MIT
  license_family: MIT
  license_file: LICENSE
  summary: Store and access your passwords safely
extra:
  copy_test_source_files: true
  final: true
  flow_run_id: db041235-c475-4190-9fb9-b44366428a34
  recipe-maintainers:
    - ccordoba12
    - licode
    - tacaswell
  remote_url: git@github.com:AnacondaRecipes/keyring-feedstock.git
  sha: 6d3b11d81180d114bdc5489cb4e82ef1f451a820
