# This file created by conda-build 3.21.4
# meta.yaml template originally from:
# /home/ktietz/src/aggregate/sphinxcontrib-jsmath-feedstock/recipe, last modified Wed Jan 27 13:09:23 2021
# ------------------------------------------------

package:
  name: sphinxcontrib-jsmath
  version: 1.0.1
source:
  sha256: a9925e4a4587247ed2191a22df5f6970656cb8ca2bd6284309578f2153e0c4b8
  url: https://pypi.io/packages/source/s/sphinxcontrib-jsmath/sphinxcontrib-jsmath-1.0.1.tar.gz
build:
  noarch: python
  number: '0'
  script: /home/ktietz/src/ci/sphinxcontrib-jsmath_1611920942228/_h_env_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_pla/bin/python
    -m pip install . --no-deps -vv
  string: pyhd3eb1b0_0
requirements:
  host:
    - _libgcc_mutex 0.1 main
    - _openmp_mutex 4.5 1_gnu
    - ca-certificates 2020.12.8 ha847dfd_0
    - certifi 2020.12.5 py39ha847dfd_0
    - ld_impl_linux-s390x 2.33.1 h8daa219_19
    - libedit 3.1.20191231 h2a837d6_0
    - libffi 3.3 hd8db5ea_2
    - libgcc-ng 9.3.0 hcace7e0_18
    - libgomp 9.3.0 hcace7e0_18
    - libstdcxx-ng 9.3.0 hc891710_18
    - ncurses 6.2 h2a837d6_0
    - openssl 1.1.1i h2a837d6_0
    - pip 20.3.3 py39ha847dfd_0
    - python 3.9.1 h76587ff_2
    - readline 8.0 h2a837d6_0
    - setuptools 51.1.2 py39ha847dfd_4
    - sqlite 3.32.3 haa4ac92_0
    - tk 8.6.10 h2795051_1
    - tzdata 2020f h52ac0ba_0
    - wheel 0.36.2 pyhd3eb1b0_0
    - xz 5.2.5 h2a837d6_0
    - zlib 1.2.11 h2a837d6_4
  run:
    - python >=3.5
test:
  imports:
    - sphinxcontrib
    - sphinxcontrib.jsmath
  requires:
    - sphinx >=2
about:
  home: http://sphinx-doc.org/
  license: BSD-2-Clause
  license_family: BSD
  license_file: LICENSE
  summary: A sphinx extension which renders display math in HTML via JavaScript
extra:
  copy_test_source_files: true
  final: true
  recipe-maintainers:
    - ocefpaf
